name        : gnome-keyring
version     : 3.18.3
release     : 8
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-keyring/3.18/gnome-keyring-3.18.3.tar.xz : 3f670dd61789bdda75b9c9e31e289bf7b1d23ba012433474790081ba7dc0ed98
license     :
    - GPL-2.0
summary     : GNOME passwords daemon
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gck-1)
    - libgcrypt-devel
    - docbook-xml
description : |
    The GNOME Keyring package contains a daemon that keeps passwords and other secrets for users.
setup      : |
    %configure --disable-static \
               --with-pam-dir=/lib/security \
               --disable-doc
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
