name       : gnome-keyring
version    : 3.34.0
release    : 15
source     :
    - https://download.gnome.org/sources/gnome-keyring/3.34/gnome-keyring-3.34.0.tar.xz : e9cda9542a3e37c61636145e7e9e2513c569092ea8020752a834e1f40ad41943
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GNOME passwords daemon
description: |
    The GNOME Keyring package contains a daemon that keeps passwords and other secrets for users.
builddeps  :
    - pkgconfig(gck-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcap-ng)
    - pkgconfig(p11-kit-1)
    - libgcrypt-devel
    - docbook-xml
    - openssh
setup      : |
    %configure --disable-doc --disable-static \
               --with-pam-dir=/lib/security
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
