name       : gnome-keyring
version    : '40.0'
release    : 19
source     :
    - https://download.gnome.org/sources/gnome-keyring/40/gnome-keyring-40.0.tar.xz : a3d24db08ee2fdf240fbbf0971a98c8ee295aa0e1a774537f4ea938038a3b931
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GNOME passwords daemon
description: |
    The GNOME Keyring package contains a daemon that keeps passwords and other secrets for users.
builddeps  :
    - pkgconfig(gck-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcap-ng)
    - pkgconfig(p11-kit-1)
    - libgcrypt-devel
    - docbook-xml
    - openssh
setup      : |
    %configure --disable-doc --disable-static \
               --with-pam-dir=/lib/security
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
