name        : gnome-keyring
version     : 3.16.0
release     : 6
source      :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-keyring/3.16/gnome-keyring-3.16.0.tar.xz : 15a3bb8c53855a4ff0dbbdfbe4ec3df206c32048f50bdc76a51f8e3e14ece1f5
homepage    : http://www.gnome.org
license     :
    - GPL-2.0
summary     : GNOME passwords daemon
builddeps   :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gck-1)
    - libgcrypt-devel
    - docbook-xsl
description : |
    The GNOME Keyring package contains a daemon that keeps passwords and other secrets for users.
setup      : |
    %configure --disable-static \
               --with-pam-dir=/lib/security \
               --disable-doc
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
