name       : gnome-keyring
version    : 3.20.0
release    : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-keyring/3.20/gnome-keyring-3.20.0.tar.xz : bc17cecd748a0e46e302171d11c3ae3d76bba5258c441fabec3786f418e7ec99
license    :
    - GPL-2.0
summary    : GNOME passwords daemon
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gck-1)
    - libgcrypt-devel
    - docbook-xml
component  : desktop.gnome
description: |
    The GNOME Keyring package contains a daemon that keeps passwords and other secrets for users.
setup      : |
    %configure --disable-static \
               --with-pam-dir=/lib/security \
               --disable-doc
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
