name       : gnome-keyring
version    : 3.36.0
release    : 16
source     :
    - https://download.gnome.org/sources/gnome-keyring/3.36/gnome-keyring-3.36.0.tar.xz : a264b57a8d1a71fdf0d66e8cd6033d013fb828be279c35766545eb9bb3734f87
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GNOME passwords daemon
description: |
    The GNOME Keyring package contains a daemon that keeps passwords and other secrets for users.
builddeps  :
    - pkgconfig(gck-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcap-ng)
    - pkgconfig(p11-kit-1)
    - libgcrypt-devel
    - docbook-xml
    - openssh
setup      : |
    %configure --disable-doc --disable-static \
               --with-pam-dir=/lib/security
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
