name       : gnome-keyring
version    : 3.28.0.2
release    : 11
source     :
    - https://download.gnome.org/sources/gnome-keyring/3.28/gnome-keyring-3.28.0.2.tar.xz : 882f12717dd2e0b37c8fda4cbe899851d83ea2cfb5b3c165f5eeed32caefa228
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GNOME passwords daemon
description: |
    The GNOME Keyring package contains a daemon that keeps passwords and other secrets for users.
builddeps  :
    - pkgconfig(gck-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(p11-kit-1)
    - libgcrypt-devel
    - docbook-xml
    - openssh
setup      : |
    %configure --disable-doc --disable-static \
               --with-pam-dir=/lib/security
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
