name       : gnome-keyring
version    : 3.31.91
release    : 13
source     :
    - https://download.gnome.org/sources/gnome-keyring/3.31/gnome-keyring-3.31.91.tar.xz : a4d90afc4dabe77c6ff8b606588ad782621df8efeb114cbdc619dc4e38a65eba
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GNOME passwords daemon
description: |
    The GNOME Keyring package contains a daemon that keeps passwords and other secrets for users.
builddeps  :
    - pkgconfig(gck-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcap-ng)
    - pkgconfig(p11-kit-1)
    - libgcrypt-devel
    - docbook-xml
    - openssh
setup      : |
    %configure --disable-doc --disable-static \
               --with-pam-dir=/lib/security
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
