name       : gnome-keyring
version    : 3.20.1
release    : 10
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-keyring/3.20/gnome-keyring-3.20.1.tar.xz : 97964e723f454be509c956ed5e38b5c2fd7363f43bd3f153b94a4a63eb888c8c
license    :
    - GPL-2.0
summary    : GNOME passwords daemon
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gck-1)
    - libgcrypt-devel
    - docbook-xml
component  : desktop.gnome
description: |
    The GNOME Keyring package contains a daemon that keeps passwords and other secrets for users.
setup      : |
    %configure --disable-static \
               --with-pam-dir=/lib/security \
               --disable-doc
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
