name       : gnome-keyring
version    : '42.1'
release    : 21
source     :
    - https://download.gnome.org/sources/gnome-keyring/42/gnome-keyring-42.1.tar.xz : c7f4d040cc76a6b7fe67e08ef9106911c3c80d40fc88cbfc8e2684a4c946e3e6
license    : GPL-2.0-or-later
component  : desktop.gnome
summary    : GNOME passwords daemon
description: |
    The GNOME Keyring package contains a daemon that keeps passwords and other secrets for users.
builddeps  :
    - pkgconfig(gck-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcap-ng)
    - pkgconfig(p11-kit-1)
    - libgcrypt-devel
    - docbook-xml
    - openssh
setup      : |
    %configure --disable-doc --disable-static \
               --with-pam-dir=%libdir%/security
build      : |
    %make
install    : |
    %make_install
    # Stateless XDG
    mv $installdir/etc/xdg $installdir/usr/share/xdg && rmdir $installdir/etc
